# Generated by Django 5.2.3 on 2025-06-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_image_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
