# Generated by Django 5.2.1 on 2025-05-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='accent_color',
            field=models.CharField(default='#0078d4', help_text='Hex color code for accent color (e.g. #0078d4)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='primary_color',
            field=models.CharField(default='#0a66c2', help_text='Hex color code for primary color (e.g. #0a66c2)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='secondary_color',
            field=models.CharField(default='#1d2226', help_text='Hex color code for secondary color (e.g. #1d2226)', max_length=7),
        ),
    ]
