# Generated by Django 5.2.1 on 2025-05-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_siteconfig_accent_color_siteconfig_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='footer_bg_color',
            field=models.CharField(default='#f8f9fa', help_text='Hex color code for footer background (e.g. #f8f9fa)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_link_color',
            field=models.CharField(default='#0a66c2', help_text='Hex color code for footer links (e.g. #0a66c2)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_text_color',
            field=models.CharField(default='#6c757d', help_text='Hex color code for footer text (e.g. #6c757d)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='heading_color',
            field=models.CharField(default='#191919', help_text='Hex color code for headings (e.g. #191919)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='heading_font_family',
            field=models.CharField(default='Arial, sans-serif', help_text='Font family for headings (e.g. Arial, sans-serif)', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='heading_font_weight',
            field=models.CharField(default='600', help_text='Font weight for headings (e.g. 600, bold)', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='navbar_bg_color',
            field=models.CharField(default='#ffffff', help_text='Hex color code for navbar background (e.g. #ffffff)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='navbar_hover_color',
            field=models.CharField(default='#0a66c2', help_text='Hex color code for navbar hover state (e.g. #0a66c2)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='navbar_text_color',
            field=models.CharField(default='#191919', help_text='Hex color code for navbar text (e.g. #191919)', max_length=7),
        ),
    ]
