# Generated by Django 5.2.1 on 2025-05-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_siteconfig_footer_bg_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to LoopedIn', max_length=100)),
                ('subtitle', models.CharField(default='Connect with friends and share your experiences', max_length=200)),
                ('sign_in_text', models.TextField(default='Sign in to access your feed, connect with friends, and more.')),
                ('register_text', models.TextField(default='Join our community today and start sharing your experiences.')),
                ('connect_heading', models.CharField(default='Connect', max_length=100)),
                ('connect_description', models.TextField(default='Find and connect with friends, family, and like-minded individuals.')),
                ('share_heading', models.CharField(default='Share', max_length=100)),
                ('share_description', models.TextField(default='Share your thoughts, experiences, and moments with your network.')),
                ('learn_heading', models.CharField(default='Learn', max_length=100)),
                ('learn_description', models.TextField(default='Discover new opportunities and grow your professional network.')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={},
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='footer_bg_color',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='footer_link_color',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='footer_text_color',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='heading_color',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='heading_font_family',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='heading_font_weight',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='navbar_bg_color',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='navbar_hover_color',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='navbar_text_color',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='secondary_color',
        ),
    ]
