# Generated by Django 5.2.1 on 2025-05-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0004_welcomecontent_alter_siteconfig_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WelcomeContent',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='connect_description',
            field=models.TextField(default='Find and connect with friends, family, and like-minded individuals.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='connect_heading',
            field=models.CharField(default='Connect', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='learn_description',
            field=models.TextField(default='Discover new opportunities and grow your professional network.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='learn_heading',
            field=models.CharField(default='Learn', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='register_text',
            field=models.CharField(default='New here? Join our community today and start sharing your experiences.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='share_description',
            field=models.TextField(default='Share your thoughts, photos, and experiences with your network.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='share_heading',
            field=models.CharField(default='Share', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sign_in_text',
            field=models.CharField(default='Already have an account? Sign in to access your feed, connect with friends, and more.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='welcome_subtitle',
            field=models.CharField(default='Connect with friends and share your experiences', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='welcome_title',
            field=models.CharField(default='Welcome to LoopedIn', max_length=100),
        ),
    ]
