# Generated by Django 5.2.1 on 2025-05-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0006_alter_siteconfig_connect_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='connect_description',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='connect_heading',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='learn_description',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='learn_heading',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='register_text',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='share_description',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='share_heading',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='sign_in_text',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='welcome_subtitle',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='welcome_title',
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload the admin interface logo (30x30px recommended)', null=True, upload_to='site_config/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo_name',
            field=models.CharField(default='LoopedIn', help_text='Name that appears in the admin interface', max_length=50),
        ),
    ]
