# Generated by Django 5.2.1 on 2025-05-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('logo_name', models.CharField(default='LoopedIn', max_length=50)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
